name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use for testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-test-workflow
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'